### ISSUE TITLE
how i can get all errors as array .

### ISSUE THREAD

**Issue by ahmedthinkdifferent** [jlbarreda/Paravaly#4]
how get all errors as array , also how i can change message without paramater () u add after every message.

**Comment by jlbarreda** [comment]
To get all the exceptions in an array you can do this:

```csharp
public void SomeMethod(string text, int x)
{
    var exceptions = RequireAll
        .Parameter(nameof(text), text).IsNotNullOrWhiteSpace()
        .AndParameter(nameof(x), x).IsGreaterThan(0)
        .ThenGetExceptions()
        .ToArray();
}
```

I'm not sure I understand your question about changing the message, but you can use a custom message this way:

```csharp
public void SomeMethod(string text)
{
    Require.Parameter(nameof(text), text).IsNotNull("Some custom error message.");
}
```

If you don't want to specify a custom message every time, you can create a custom validation.
